### ISSUE TITLE
Game lags when near portals

### ISSUE THREAD

**Issue by MrCrow64** [thefinalcutbg/IveGotSomeBalls#1]
the game drops to 1-5 fps after a few seconds into a level where there's a triangular portal, the frame drop only happen when I'm near the portals.
I'm also rendering the game in opengl3 because my graphic driver doesn't support vulkan so maybe that's what causing the issue idk..
I get this error on loop in the cmd terminal when the frames drop : 

ERROR: Condition "!sli" is true. Continuing.
   at: _shadow_atlas_find_shadow (drivers/gles3/storage/light_storage.cpp:954)

and those errors when I exit the game : 

ERROR: 1 RID allocations of type 'N20RasterizerSceneGLES33SkyE' were leaked at exit.
ERROR: Pages in use exist at exit in PagedAllocator: N20RasterizerSceneGLES323GeometryInstanceSurfaceE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
ERROR: Pages in use exist at exit in PagedAllocator: N20RasterizerSceneGLES321GeometryInstanceGLES3E
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
ERROR: 1 RID allocations of type 'N26RendererEnvironmentStorage11EnvironmentE' were leaked at exit.
ERROR: 2 RID allocations of type 'N5GLES312LightStorage11ShadowAtlasE' were leaked at exit.
ERROR: 3 RID allocations of type 'N5GLES34MeshE' were leaked at exit.
ERROR: 4 shaders of type SceneShaderGLES3 were never freed
   at: ~ShaderGLES3 (drivers/gles3/shader_gles3.cpp:817)
ERROR: 5 RID allocations of type 'N5GLES38MaterialE' were leaked at exit.
ERROR: 4 RID allocations of type 'N5GLES36ShaderE' were leaked at exit.
ERROR: 2 RID allocations of type 'N5GLES312RenderTargetE' were leaked at exit.
ERROR: 11 RID allocations of type 'N5GLES37TextureE' were leaked at exit.
ERROR: Texture with GL ID of 19: leaked 21872 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:79)
ERROR: Texture with GL ID of 85: leaked 4626056 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:79)
ERROR: Texture with GL ID of 86: leaked 699064 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:79)
ERROR: Texture with GL ID of 93: leaked 3496000 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:79)
ERROR: Texture with GL ID of 94: leaked 2622000 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:79)
ERROR: Texture with GL ID of 95: leaked 4000000 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:79)
ERROR: Texture with GL ID of 96: leaked 3000000 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:79)
ERROR: Texture with GL ID of 97: leaked 2097152 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:79)
ERROR: Texture with GL ID of 98: leaked 2796202 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:79)
ERROR: Texture with GL ID of 99: leaked 349524 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:79)
ERROR: Texture with GL ID of 100: leaked 349524 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:79)
ERROR: Texture with GL ID of 101: leaked 4659436 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:79)
ERROR: Texture with GL ID of 102: leaked 524288 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:79)
ERROR: Texture with GL ID of 108: leaked 524288 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:79)
ERROR: Buffer with GL ID of 25: leaked 44200 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:95)
ERROR: Buffer with GL ID of 26: leaked 17680 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:95)
ERROR: Buffer with GL ID of 27: leaked 25344 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:95)
ERROR: Buffer with GL ID of 28: leaked 54080 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:95)
ERROR: Buffer with GL ID of 29: leaked 21632 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:95)
ERROR: Buffer with GL ID of 30: leaked 31212 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:95)
ERROR: Buffer with GL ID of 31: leaked 80 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:95)
ERROR: Buffer with GL ID of 32: leaked 32 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:95)
ERROR: Buffer with GL ID of 33: leaked 12 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:95)
ERROR: 21 RID allocations of type 'N18RendererCanvasCull4ItemE' were leaked at exit.
ERROR: 2 RID allocations of type 'N18RendererCanvasCull6CanvasE' were leaked at exit.
ERROR: 2 RID allocations of type 'N16RendererViewport8ViewportE' were leaked at exit.
ERROR: 4 RID allocations of type 'N17RendererSceneCull8InstanceE' were leaked at exit.

I'm running the game on a pretty old laptop with low end specs using windows 10 so I hope that's not the cause of the issue with frames because I really want to play this, I've been looking for it for years but was unable to find it until somewhat recently I was really looking forward to playing but was disappointed that it doesn't run on windows 10 and then I discovered your remake and that gave me hope that I was finally able to relive this game again, so I really hope you could help me to figure out the problem and thanks remaking this game.

**Comment by thefinalcutbg** [comment]
According to [Godot website](https://docs.godotengine.org/en/stable/about/system_requirements.html#id1) the minimum GPU requirement is full Vulkan 1.0 support. The game runs on lower-end GPUs but frame drops are expected. The engine is not mine, so there's nothing I can do, sorry :(

**Comment by MrCrow64** [comment]
Understandable, thanks for the reply and and thanks again for creating this.. I hope to get a new pc to be able to play this in the future.
